### ISSUE TITLE
Missing JSDoc Comments in the `ExerciseScreen.jsx`

### ISSUE THREAD

**Issue by ITPini** [Educado-App/educado-mobile#124]
## Issue Description

The `ExerciseScreen.jsx` screen component is missing JSDoc comments. 

## Steps to Reproduce

1. Navigate to `eml/screens/exercise/ExerciseScreen.jsx`.
2. Observe the absence of JSDoc comments for functions and their parameters.

## Expected Behavior:
Each function within `ExerciseScreen.jsx` should have JSDoc comments as according to DoD.

## Additional Information
`ExerciseScreen.jsx` is currently missing this documentation.

- **Environment**: Mobile

**Comment by benceisonline** [comment]
fixed and pushed to dev with PR
