### ISSUE TITLE
Cannot view courses without subscribing to it (might be intentional)

### ISSUE THREAD

**Issue by JackSMunn** [Educado-App/educado-mobile#129]
## Issue Description

Can't access courses without subscribing in explore (Is this a decision that is made on purpose, or are you forced to subscribe?)

## Steps to Reproduce

1. Log into app
2. Navigate to explore page
3. Try to access the content of a course without subscribing (you can't)

## Expected Behavior

You can "explore" the content without subscribing to it

## Actual Behavior

You can't "explore" the content without subscribing to it

## Additional Information

Environment: Latest APK that is used in user test.
https://expo.dev/artifacts/eas/pNQkJgYHNm7tmswempH5Sr.apk

**Comment by PrometheusBork** [comment]
If I remember correctly Luiza said that she did not want users to access the contents of courses without being subscribed

**Comment by sofiiagran** [comment]
We can close this issue as this is intentional and something Luiza wanted
