### ISSUE TITLE
After answering something in an exercise, you cannot "redo" the answer

### ISSUE THREAD

**Issue by JackSMunn** [Educado-App/educado-mobile#136]
## Issue Description

Can't press on other options when you have clicked on something in the exercises. --> Can't fix wrong answers. 

Eg. when you have chosen an answer for an exercise, you cannot press on another answer to "fix it". Is it 

## Steps to Reproduce

1. Login 
2. Navigate to explore page
3. Navigate into a course
4. Navigate to a specific exercise
5. Answer the exercise
6. Observe that you cannot change the answer once  you have submitted and gotten feedback

## Expected Behavior

You can change the answer to better align mental models. In my opinion, it is better if they can change the answer after. 

## Actual Behavior

You can't change the answer after.

## Additional Information

Environment: Latest APK that is used in user test.
https://expo.dev/artifacts/eas/pNQkJgYHNm7tmswempH5Sr.apk

**Comment by benceisonline** [comment]
The user should not be able to change their answer, so the behaviour is correct. This was also discussed with the product owner.

**Comment by amaliedilling** [comment]
Doesn't need fixing
