### ISSUE TITLE
Nativewind styling does not seem to be applied

### ISSUE THREAD

**Issue by MortenMunk** [Educado-App/educado-mobile#161]
## Issue Description

Nativewind styling does not seem to be applited

## Steps to Reproduce

1. open the app
2. notice that fx. text fields does not have a color anymore, and button text is black and not white

## Expected Behavior

styles should be applied to fx. text fields and buttons

## Actual Behavior

styles are not applied it seems

## Additional Information

- **Environment**: Android Studio
- **Screenshots**: 
- ![image](https://github.com/Educado-App/educado-mobile/assets/92527083/fce62de5-6524-4d7f-8721-1f7fc7b04804)

**Comment by ITPini** [comment]
Closing this issue - This issue has been addressed in PR #209 

<img width="300" src="https://github.com/Educado-App/educado-mobile/assets/43484432/b8dbf84f-0b39-4ee7-9bd7-610768a8c00d">
