### ISSUE TITLE
Login toast message

### ISSUE THREAD

**Issue by sofiiagran** [Educado-App/educado-mobile#195]
## Issue Description

The login toast message shows up after navigating to section screen from exercise screen. 

## Steps to Reproduce

1. Start a section with lectures and exercises
2. Complete lectures and exercises
3. Click on the animation button that says "continue"
4. Then you are navigated back to section screen
5. The toast message that says "login successo"

## Expected Behavior

The toast message should only pop-up when you log in

## Actual Behavior

The toast message also pop-up at other points

**Comment by PrometheusBork** [comment]
Closing this as it has been fixed in PR #208
