### ISSUE TITLE
Weird error with CompleteCourseSlider

### ISSUE THREAD

**Issue by sofiiagran** [Educado-App/educado-mobile#228]
## Issue Description

I get this error:  ERROR  Warning: Failed prop type: Invalid prop `onIndexChanged` of type `function` supplied to `CompleteCourseSlider`, expected `number`. 

## Steps to Reproduce

1. Finish a section (the last section of the first course)
2. Go back and finish it again
3. Voila. Error.

## Expected Behavior

I do not want error

## Actual Behavior

I get error :(

## Additional Information

Uses dev and staging backend (backend should be up to date)

**Comment by benceisonline** [comment]
pushed hotfix for error type
