### ISSUE TITLE
[App - Profile] As a waste picker, I want to access easily my profile

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#258]
Description:
Difficulty locating the profile page

Solution Proposal:
Review the icon of profile or change the colors to make it more highlighted

Improvement Priority Number: 18

**Comment by magnusklundgren** [comment]
### User Test:
**Scenario 1: Profile Page Location**

Steps:

- User navigates to the main application screen.
- User attempts to locate the profile page.

Expected Outcomes:

- The profile page icon or button is easily identifiable and accessible.
- The user can quickly locate and navigate to the profile page.
