### ISSUE TITLE
[App - Course / Gamification] As a waste picker, I want to see me getting points after completing exercises on a course

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#260]
Description:
1. The animation at the end of the course is the same as the animation during the activity modules; 
2. The animations are not very motivating; 
3. When you get all the questions right at the end there is a bug with the course screen flashing green and red.

Solution Proposal:
Review course animations and develop new ones (add sounds, colors, animations)

Bug Priority Number: 6

Comments:
split up into bugs and improvements

**Comment by Frederik-Lauridsen** [comment]
@iarandrd @benceisonline 
It is impossible to test before the progress logic of sections, courses etc. is done correctly. As of now, there is way too much logic that has to be fixed for this to be tested. To name a few:

1. Points aren't collected at the end of a course
2. Courses aren't updated correctly so there is no way to update the progress - therefore an animation cannot be tested or changed to know if it works. 
3. Courses are automatically completed to some degree depending on how many videos or text pages it has. Exercises cannot be updated to complete as of now.

**Comment by Andersraae** [comment]
On hold until section view page does not crash

**Comment by Lowkee1g** [comment]
After talkes with @iarandrd the criteria has been changed for this PBI to the following:
### Recent Changes for Course Completion Animations:

#### Current Animations:
1. A trophy animation appears after completing each section.
2. When a course is completed, the following animations are shown: a rocket, percentage completion, and certificate.

#### Planned Changes:
1. Add a rating and feedback screen after course completion (managed by another team). Ensure space is allocated for this screen.
2. Review and possibly reduce the number of animations/screens to keep them relevant and impactful.
3. Consider removing the "Complete 2" animation if it does not add value.
4. Modify the "Complete 1" animation by removing text, adding a link to the certificate, or incorporating points from the trophy animation. This animation would also include a "Continue" button that leads to the feedback-rating page.
5. The trophy animation will be skipped if there is only 1 section in a course
