### ISSUE TITLE
[App - Course] Inicial course structure

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#263]
As a waste picker, I want to understand the dynamics of the course

Problem: The dynamics after subscribing to a course were not intuitive. They didn’t understand thay the course started just on the first screen because it went direct to the first course page

Solution Proposal: Add post-registration animation with start now button

Improvement Priority Number: 1

**Comment by magnusklundgren** [comment]
Acceptance criteria:

- There should be an intermediate screen with and animation which communicates that the waste picker is subscribed to the course

**Comment by magnusklundgren** [comment]
User tests:

- TODO

**Comment by magnusklundgren** [comment]
Translations needed:

- Start course now
- Start course later
- You are now subscribed to this course

**Comment by iarandrd** [comment]
Start course now = Começar agora 
Start course later = Começar depois
You are now subscribed to this course = Parabéns! Você está inscrito no curso "**course-name**"
