### ISSUE TITLE
[App - Sections] Course section navigation

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#265]
As a waste picker, I want to navigate to lectures and exercises from the section screen

Description: Propose new experience to the Course Sections so the user can see all section, all classes inside the sections, user can start a specific class our continue form where stopped, user can download classes or the course 

Improvement Priority Number: 14

**Problem Statement:** Users need a better way to navigate through courses. Currently, the navigation between sections, classes, and exercises is not intuitive, and users may have difficulty finding where they left off or accessing specific content. A new user experience is required to streamline navigation and improve accessibility to course content.

**Goal:** Allow users to easily navigate through course sections, access specific classes or exercises, continue from where they left off, and download course content for offline use. The new experience should follow the proposed UI design and enhance the flow through the sections and classes.

**Scope:**
- New navigation for course sections, allowing users to view all sections and classes/exercises within each section.
- Users can start a specific class or continue from where they stopped.
- Classes must be blocked if previous classes have not been completed.
- Allow users to download courses, sections, or individual classes/exercises.
- Display progress for each course, and allow users to remove a course if desired.

**Solution Ideas:** Figma: ask for the link when start working on it 

**Success Criteria:**
- Users can seamlessly navigate between sections, classes, and exercises.
- Users can download courses, sections, or individual classes for offline use.
- Progress is tracked accurately, and users can see where they left off.
- Classes are blocked if the previous ones haven't been completed.

**Comment by luisaleaol** [comment]
Hi, everyone! Here's the section linf :)

https://www.figma.com/design/BCEVQYvMDrcBE9qqehr9HL/Mobile-Education-UI?node-id=6459-4809&t=mQSmIGf1UjzbyDxx-4
