### ISSUE TITLE
[App - Sections] Download course, class or exercise

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#270]
**Problem Statement:** Users need the ability to download course materials, classes, or exercises to access them offline. Currently, the download functionality is either unclear or difficult for users to find and understand, which limits the use of the offline access feature.

**Goal:** Users should be able to easily identify the download button and choose whether they want to download an entire course, a specific section, or individual classes/exercises. The download process should be simple and intuitive to allow offline access without confusion.

**Scope:**
- Redesign the download icon to make it more recognizable and user-friendly
- Users should be able to download by course, section, or individual class/exercise
- Offline functionality must allow full access to downloaded content, including video, text, and exercises. (communicate with the group responsible for the download page)

**Solution Ideas:**
- Consider using a more universally recognized download icon, such as a downward arrow
- Ensure that the download size and estimated time are displayed before confirming the download
- Consider adding an option in the user guide explaining how to download and access content offline (communicate with the group responsible for the new users onboarding)

**Risks and Unknowns:**
- Users with limited storage space may struggle to download large files like entire courses.
- Offline functionality might become complex if users attempt to download multiple sections or classes simultaneously.

Success Criteria:
- Users can successfully download and access entire courses, sections, or individual classes/exercises offline
- The new download icon is easily identified and understood by users
- The download process is smooth, with no confusion about what content is being downloaded

**Comment by davidfraenkel** [comment]
https://github.com/user-attachments/assets/0472646a-2dd0-43a6-9a76-af38c743d867
