### ISSUE TITLE
[App - Home] Continue course where stopped

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#286]
As a waste picker, after closing the application, when I press home and click in a course that I am subscribed, I want to go back to the last screen I opened of a course to continue where I left off

**Comment by Jenspetersen99** [comment]
**Resume Course**
When the user reopens the app and clicks on a subscribed course, they should be taken back to the exact screen they were on before closing the app.
**Save Progress**
The app should automatically save the user's position in the course (e.g., lesson, video, quiz) when they leave or close the app.
**Quick and Seamless**
The user should be able to continue their course without any extra steps when returning to the app.
**Offline Support**
If the app is offline, it should still save the user's last position and allow them to continue when back online.
**Fallback to Last Lesson**
If the app can't save the exact screen, it should at least take the user to the last completed lesson.
This makes sure users can quickly return to where they left off in the course without complications.
