### ISSUE TITLE
[App - Profile] Leaderboard

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#294]
Problem Statement: Users are motivated by recognition and friendly competition. Currently, there is no visible way for users to see how their efforts compare to others, which could decrease engagement with the app and reduce motivation to participate in courses and activities.

Goal: Provide waste pickers with a leaderboard that ranks users based on their total points on a monthly basis. This feature aims to encourage competition, drive participation, and foster a sense of community among users.

Scope:
- Display the user's current rank and total points on the main profile page.
- Include a button labeled "View Full Leaderboard" that redirects users to a new page showing the complete rankings.
- On the full leaderboard page: List all users ranked by their total points, Highlight the logged-in user’s position for easy identification.
- Allow scrolling through the list for a better user experience.

Solution Ideas:
- Main profile leaderboard section could display avatars or initials, names, and point totals of the top 3 users.
- Use a consistent design pattern for navigation between the profile and leaderboard pages.
- Implement infinite scrolling for the full leaderboard page to handle many users.

Risks and Unknowns:
- Performance risks when handling a large user base and real-time updates to rankings.
- Potential need for server-side optimizations to calculate and display rankings efficiently.
- Ensuring user data (e.g., profile visibility) complies with any privacy preferences.

Success Criteria:
- Users can access a full leaderboard that accurately reflects point totals.
- The user’s rank and points are prominently displayed in both views.

Considerations:
- Ensure leaderboard refreshes periodically (e.g., every few minutes) to display accurate rankings.
- Provide clear indications that the leaderboard resets at the beginning of each month (check about this).
- Maintain accessibility features to ensure the leaderboard is usable by all users, including those with visual impairments.

**Comment by Thomass1412** [comment]
Acceptence Criteria: 

- Leaderboard page that displays your current ranking, with a view of all users. (should be accessible from where?)
- Top 3 users should be visible at all times on this page, with avatar and name 
- Leaderboard should be refreshed monthly, should be clearly stated and calculated server-side to avoid cheating. Will be updated each time the page is refreshed 
- Your ranking should be visible on your profile

**Comment by luisaleaol** [comment]
Here's the link for this section: https://www.figma.com/design/BCEVQYvMDrcBE9qqehr9HL/Mobile-Education-UI?node-id=7713-17908&t=BIPAPHmfs8qGpScs-4
