### ISSUE TITLE
[App - Course] Rate and feedback

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#301]
**Problem Statement:** Users need a way to provide feedback on their learning experience after completing a course. Currently, there is no option for users to rate courses or leave comments, which prevents collecting valuable insights to improve the content and user experience.

**Goal:** Allow users to rate a course and leave written feedback once it has been completed. This will provide a better understanding of user satisfaction and areas for course improvement.

**Scope:**
- A rating system (e.g., stars, thumbs up/down) that users can interact with after finishing a course
- A text box for users to provide feedback about their experience
- Ensure feedback is optional, but the rating system is mandatory to submit

**Solution Ideas:**
- Use a 5-star rating system with an optional text box where users can describe what they liked or didn’t like about the course
- After completing a course, show a simple pop-up or screen prompting users to rate the course
- Store the feedback and ratings in the database for analysis by content creators in the website dashboard

**Risks and Unknowns:**
- Users might skip the feedback process if it feels too time-consuming or intrusive
- Ensuring that feedback collected is constructive and not abusive could be a challenge without moderation

**Success Criteria:**
- Users can successfully rate a course upon completion
- Users can provide optional feedback in a text box
- Ratings and feedback are stored and accessible for future review by course creators

**Comment by magnusklundgren** [comment]
Proposed Solution:

- 5-star system: Mandatory rating.
- Dropdown menu: Users select predefined feedback options.
- Text box: Optional for additional feedback.

Acceptance Criteria:

Dropdown Menu:
- Users can select one or more options from the dropdown menu.
- The dropdown menu options are clear and relevant to the course experience.

Text Box:
- Users can enter text into the optional text box.
- The text box is clearly labeled and its purpose is explained.

5-Star System:
- Users can select a rating from 1 to 5 stars.
- The rating system is visually prominent and easy to use.

Feedback Submission:
- Users can successfully submit their feedback (rating and optional text).
- A confirmation message is displayed upon successful submission.

Data Storage:
- Ratings and feedback are stored in the database.

Feedback visibility:
- The top 2 categories of the predefined options are shown as labels on the course.
