### ISSUE TITLE
[App - Download] Download environment

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#309]
**Problem Statement:** Users need access to courses they’ve downloaded while offline or when they don’t want to use the internet. Currently, there is no option to store or access courses offline temporarily, limiting their ability to study when internet access is unavailable. Users also need a way to manage and delete downloaded content, with the option for automatic removal after a set period.

**Goal/Outcome:** Enable users to download and access courses offline. When offline, users should only see content they’ve downloaded. The app should store the content temporarily and delete it automatically after one month unless the user chooses to delete it manually.

**Scope:** 
- Offline mode displaying only downloaded courses
- Functionality to download courses temporarily when the user has internet access
- The option for users to delete downloaded content manually
- Automatic deletion of downloaded content after one month

**Solution Ideas:**
- Display an "Offline Mode" or "Downloads" page that shows only downloaded courses when the user is offline
- Access that page through the profile page 
- Store downloads in local storage with a timestamp, and set a rule to automatically delete content after 30 days (conversation with the group responsible for the content download)
- Notify users when content is about to be deleted, with an option to refresh the download if needed
- Ensure downloads include all necessary assets (video, text, exercises) for offline access

**Risks and Unknowns:**
- Limited storage on users’ devices may affect the amount of content that can be downloaded
- Edge cases could arise when users partially download courses or face connectivity issues while downloading

Success Criteria:
- Users can access and interact with downloaded courses when offline
- Users can manually delete downloaded content, and the app automatically deletes it after one month
- When offline, the app switches to “Offline Mode” and displays only downloaded content

**Additional Notes:**
- Ensure that the download feature works seamlessly on devices with varying storage capacities
- Communicate with the group responsible for the download to understand the course, class and exercises download rules and that will reflect in the interface

**Comment by davidfraenkel** [comment]
### Acceptance critea
- [ ] App switches to "Offline Mode" when offline, displaying only downloaded content.
- [ ] "Downloads" page is accessible from the profile page, showing downloaded courses.
- [ ] Download status and progress are visible.
- [ ] Users can manually delete downloaded courses from the "Downloads" page.
- [ ] Downloaded content auto-deletes after 30 days

**Comment by davidfraenkel** [comment]
https://github.com/user-attachments/assets/f88b0f6a-cd41-48ce-a49f-8148410863d6
