### ISSUE TITLE
[App - New User] Onboarding steps

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#329]
**Problem Statement:** New users often face difficulties learning how to navigate the app, which can lead to frustration and reduced engagement. A structured onboarding guide is needed to introduce users to the app’s key features and ensure they can start using it smoothly.

**Goal:** Create an onboarding guide that helps new users understand how to navigate the app. The guide should walk them through the most important features and actions step by step, ensuring they feel comfortable using the app independently by the end of the process.

**Scope:** 
- A step-by-step interactive onboarding guide for new users
- Highlight key features such as course subscription, course navigation, downloading content for offline use, accessing the virtual tutor, etc
- Ensure the onboarding guide only appears for first-time users or when reactivated from settings
- Exclude detailed tutorials for every feature (focus on key actions only for this version)

**Solution Ideas:**
- Use interactive tooltips or guided walkthroughs to highlight key areas of the app (e.g., “Tap here to view your courses”)
- Incorporate progress indicators or checklists or step numbers (check web solution) so users can see how far they’ve gone in the onboarding process
- Include an option to skip or revisit the onboarding later from the app’s settings

**Risks and Unknowns:**
- Users may skip the onboarding if it feels too long or unnecessary

**Success Criteria:**
- New users are able to complete key actions (e.g., finding courses, downloading content) with ease after going through the onboarding guide
- The onboarding process is short, clear, and does not overwhelm users

**Comment by Thomass1412** [comment]
### Proposed Solution 

Have a popup with a background overlay that highlights key features and navigates the app 

### Acceptence criteria 

- When loggin in for the first time the user goes through onboarding steps 
- The user can skip the steps if they wish, and can retake the process from settings 
- The onboarding steps should show atleast: Profile, Certificates, Courses, How to subscribe to a course

**Comment by luisaleaol** [comment]
Hi, everyone! Here's the section link to the onboarding steps :)
