### ISSUE TITLE
[App - Course] Update handle last component

### ISSUE THREAD

**Issue by BabaWolo** [Educado-App/educado-mobile#358]
Currently, the function handleLastComponent is responsible for ending the course and generating a certificate upon completion.

The function is called whenever a component is the last in its corresponding section.

Issue:
- We don't check the course for multiple sections and/or unfinished sections. Meaning we try to generate a certificate and end a course while its unfinished.

Fix:
- We should check both for subsequent sections in the course and ensure that all other sections in the course are completed before calling handleLastComponent

**Comment by BabaWolo** [comment]
@iarandrd 

This is a general bug found in the app, please review and possibly update :)

**Comment by Laskiri** [comment]
<img width="404" alt="image" src="https://github.com/user-attachments/assets/8f414646-adad-455f-9888-274883cbefda">
Can you guys remove this function in sectionComplete as HandleLastComponent already navigates to CourseComplete so it's redundant to also have in sectionComplete

**Comment by Laskiri** [comment]
> <img alt="image" width="404" src="https://private-user-images.githubusercontent.com/105007826/384365966-8f414646-adad-455f-9888-274883cbefda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjg5MzksIm5iZiI6MTczMTA2ODYzOSwicGF0aCI6Ii8xMDUwMDc4MjYvMzg0MzY1OTY2LThmNDE0NjQ2LWFkYWQtNDU1Zi05ODg4LTI3NDg4M2NiZWZkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxMjIzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzE3OTFhMzg1ZDFkMmYwYmM2ZTJmOWMxNzdiMzg4MDYzYWNjZThiOTgzZDBmMmUyYzFkMzAxNTY1ZWU1MDdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yPu0g_pGHkmYtuyf-imtaQnWqGkZj4b95ylqZ6Cg6ho"> Can you guys remove this function in sectionComplete as HandleLastComponent already navigates to CourseComplete so it's redundant to also have in sectionComplete

also the isCourseCompleted function is broken so it makes no sense using it

**Comment by BabaWolo** [comment]
@Laskiri, please be aware that this has not yet been confirmed as a valid PBI/Issue, and no one is currently assigned since it’s still pending Iara’s review.

Feel free to add any additional notes for context, but please aim to keep the details clear and objective.

Let me know if you’d like any further adjustments!
