### ISSUE TITLE
Incorrect navigation from welcome page to register page

### ISSUE THREAD

**Issue by MortenMunk** [Educado-App/educado-mobile#62]
## Issue Description

Incorrect navigation from welcome page, as it does not navigate to register page, when clicking "cadastrar"

## Steps to Reproduce

1. Open app for the first time (welcome page is accessed)
2. click "cadastrar"

## Expected Behavior

- navigate to register page

## Actual Behavior

- navigated to login page

## Additional Information

- **Android Studio**: 
<img width="191" alt="image" src="https://github.com/Educado-App/educado-mobile/assets/92527083/0956f75d-b66a-4121-ba8d-f8dd9f0e7497">

**Comment by benceisonline** [comment]
done <3
