### ISSUE TITLE
PNG's are used instead of icons

### ISSUE THREAD

**Issue by MortenMunk** [Educado-App/educado-mobile#65]
## Issue Description

Several PNG's has been imported to the project, rather than the agreed icons

## Steps to Reproduce

1. check mobile assets

## Expected Behavior

Icons should be Material icons

## Actual Behavior

Icons are imported as PNG images

## Additional Information

- **Environment**: Android Studio

**Comment by benceisonline** [comment]
Arrow left, arrow right (fjern styleguide, dupe logo)
See passwordEye

**Comment by benceisonline** [comment]
pushed fix <3

**Comment by benceisonline** [comment]
pushed fix <3
