### ISSUE TITLE
[Team Offline] Dependency on explore page

### ISSUE THREAD

**Issue by sofiiagran** [Educado-App/educado-mobile#72]
## Issue Description

We are facing dependency on the explore page to be merged to dev.
We are responsible for the functionality of the subscribe button, the code has been fully tested and is a part of PR #71, which will soon be merged into dev. However, since there is no UI for the explore page in dev right now, the functionality cannot be implemented. 

## Expected Behavior

You will click the subscribe button on the explore page, which will then call the code that will subscribe the currently logged-in user to the course clicked on.

## Actual Behavior

There is no explore page in dev, and therefore, there is nowhere the subscribe functionality can be implemented.

**Comment by ITPini** [comment]
Pull request #115 has addressed this dependency
