### ISSUE TITLE
Unnecessary Pass of State to Function

### ISSUE THREAD

**Issue by ITPini** [Educado-App/educado-mobile#93]
## Issue Description

There are functions in the `RegisterForm.js` component where the component state is being passed explicitly as function arguments even though they can be accessed directly from within the function.

## Steps to Reproduce

1. Navigate to `eml/components/login/RegisterForm.js`.
2. Inspect the `register` function. 
https://github.com/Educado-App/educado-mobile/blob/21ae5c9d759eb0cff05baa523231a78a06506f9a/eml/components/login/RegisterForm.js#L143
The state values `firstName`, `lastName`, `email` and `password` are being passed explicitly.

4. Note that these state values can be directly accessed from within the function and do not need to be passed as parameters. 
https://github.com/Educado-App/educado-mobile/blob/21ae5c9d759eb0cff05baa523231a78a06506f9a/eml/components/login/RegisterForm.js#L27-L30

## Expected Behavior

Functions should utilize the component's state directly when necessary, rather than having them passed explicitly as arguments, to make the code cleaner and more readable.

## Actual Behavior

The register function is explicitly receiving state variables as arguments, adding unnecessary redundancy to the code.

## Additional Information

- **Environment**: Mobile

**Comment by MortenMunk** [comment]
@ITPini Can you check if this issue is fixed on current version of dev? My IDE says that these parameters are used.

**Comment by MortenMunk** [comment]
fixed in current version of dev
