### ISSUE TITLE
Refactor Hardcoded Styles in `LoginForm.js` Component

### ISSUE THREAD

**Issue by ITPini** [Educado-App/educado-mobile#96]
## Issue Description

In the `LoginForm` component, there are instances where styles are hardcoded directly into the JSX

## Steps to Reproduce

1. Navigate to `eml/components/login/LoginForm.js`.
2. Observe the hardcoded styles such as `ml-[205px]` within the component.
https://github.com/Educado-App/educado-mobile/blob/21ae5c9d759eb0cff05baa523231a78a06506f9a/eml/components/login/LoginForm.js#L132

## Additional Information

- **Environment**: Mobile

**Comment by MortenMunk** [comment]
Fixed in current version of dev 😄🥇
